version: "3.6"
services:
  webapi:
    build: .
    command: python3 -u app.py
    ports:
    - "5000:5000"
    volumes:
    - .:/leadbook
    links:
    - leadbookdb
  leadbookdb:
    image: mongo:4.0.4